# Generated by Django 5.1.6 on 2025-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('enrollment_requirements', models.TextField()),
                ('meeting_times', models.JSONField()),
                ('room', models.CharField(max_length=100)),
                ('prerequisites', models.ManyToManyField(blank=True, to='home.collegecourse')),
            ],
        ),
    ]
