# Generated by Django 5.2.1 on 2025-05-07 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecourse',
            name='credits',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='major',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(blank=True, related_name='schedules', to='home.collegecourse')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('freshman_fall', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freshman_fall_schedule', to='home.schedule')),
                ('freshman_spring', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freshman_spring_schedule', to='home.schedule')),
                ('junior_fall', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_fall_schedule', to='home.schedule')),
                ('junior_spring', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_spring_schedule', to='home.schedule')),
                ('senior_fall', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_fall_schedule', to='home.schedule')),
                ('senior_spring', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_spring_schedule', to='home.schedule')),
                ('sophomore_fall', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sophomore_fall_schedule', to='home.schedule')),
                ('sophomore_spring', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sophomore_spring_schedule', to='home.schedule')),
            ],
        ),
    ]
