# Generated by Django 5.2.1 on 2025-05-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_collegecourse_credits_collegecourse_major_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecourse',
            name='advisorRecs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='semester',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='enrollment_requirements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='room',
            field=models.CharField(default='', max_length=100),
        ),
    ]
