# Generated by Django 5.2.1 on 2025-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_collegecourse_advisorrecs_collegecourse_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourse',
            name='semester',
            field=models.CharField(default='', max_length=11),
        ),
    ]
